// 查询返回的看板数据
var boardData = {
  id: 3,
  userId: '1',
  categoryId: null,
  name: '大屏',
  userName: 'Administrator',
  loginName: null,
  createTime: '2021-09-30 09:58:25.0',
  updateTime: '2021-09-30 09:58:25.0',
  layout: {
    rows: [
      {
        type: 'widget',
        widgets: [
          {
            positionY: '7',
            border: 'url(imgs/cockpit/border/01.png)',
            chartWidth: '27',
            widget: {
              data: {
                datasetId: 7,
                config: {
                  valueAxis: 'vertical',
                  chart_type: 'line',
                  keys: [
                    {
                      col: 'province',
                      level: 'GEO',
                      values: [],
                      id: '983188c3-ade1-48ee-8d33-53239ae271bf',
                      type: 'eq',
                    },
                  ],
                  values: [
                    {
                      name: '',
                      series_type: 'line',
                      type: 'value',
                      cols: [{ col: 'cnt', aggregate_type: 'sum' }],
                    },
                  ],
                  groups: [],
                  filters: [],
                  coordinateSystem: 'cartesian2d',
                  option: { dataZoom: false, gridCustom: false, legendShow: true },
                },
                expressions: [],
                filterGroups: [],
              },
              createTime: '2021-09-30 09:55:37.0',
              edit: false,
              loginName: null,
              name: 'TEST_CAHRT',
              updateTime: '2021-09-30 09:55:37.0',
              id: 16,
              userName: null,
              categoryName: '默认分类',
              delete: false,
              userId: '1',
            },
            roleInfo: [],
            bgColor: 'none',
            widgetId: 16,
            name: 'TEST_CAHRT',
            domId: 'chart_1632966987527',
            show: false,
            chartHeight: '23',
            positionX: '2',
          },
          {
            positionY: '2',
            border: 'url(imgs/cockpit/border/01.png)',
            chartWidth: '51',
            widget: {
              data: {
                datasetId: 2,
                config: {
                  chart_type: 'scatter',
                  keys: [
                    {
                      col: 'SALES_COUNTRY',
                      level: 'Geo',
                      values: [],
                      alias: 'country',
                      sort: 'asc',
                      id: '4abf2747-3024-44bc-88ef-3cc2643d2b09',
                      type: 'eq',
                    },
                    {
                      col: 'SALES_REGION',
                      level: 'Geo',
                      values: [],
                      alias: 'region',
                      sort: 'asc',
                      id: '9f85f220-3728-468c-8e0e-a5e88a3a9b23',
                      type: 'eq',
                    },
                  ],
                  values: [
                    { name: '', cols: [{ col: 'store_cost', aggregate_type: 'sum' }] },
                    { name: '', cols: [{ col: 'store_sales', aggregate_type: 'min' }] },
                    { name: '', cols: [{ col: 'unit_sales', aggregate_type: 'count' }] },
                  ],
                  groups: [
                    {
                      col: 'SALES_DISTRICT',
                      level: 'Geo',
                      values: [],
                      alias: 'district',
                      sort: 'asc',
                      id: 'b0c8d29b-9f53-41d4-95b7-132f1e4c876b',
                      type: 'eq',
                    },
                  ],
                  filters: [],
                },
                expressions: [],
                filterGroups: [],
              },
              createTime: '2019-09-22 17:33:12.0',
              edit: false,
              loginName: null,
              name: 'Bubble',
              updateTime: '2019-09-22 17:33:12.0',
              id: 9,
              userName: null,
              categoryName: 'Demo',
              delete: false,
              userId: '1',
            },
            roleInfo: [],
            bgColor: 'none',
            widgetId: 9,
            name: 'Bubble',
            domId: 'chart_1632966997721',
            show: false,
            chartHeight: '18',
            positionX: '47',
          },
        ],
      },
      {
        type: 'other',
        others: [
          {
            positionY: '75',
            chartWidth: '21',
            jsonData: {},
            chartStyle: '',
            cockpitConfChartCSS: {
              textFontSize: '12',
              labelPadding: '5',
              labelFontSize: '12',
              textFontWeight: 'normal',
              textColor: '#FFFFFF',
              labelColor: '#FFFFFF',
              textFormat: 'yyyy-MM-dd hh:mm:ss',
            },
            domId: 'clock_1632967073624',
            type: 'clock',
            chartHeight: '17',
            positionX: '2',
          },
          {
            positionY: '41',
            chartWidth: '21',
            jsonData: { value: 'HexCockpit可视化产品，创造属于您的日常运营监控大屏！' },
            chartStyle: '',
            cockpitConfChartCSS: { titleColor: '#FFFFFF' },
            domId: 'rlabel_1632967077811',
            type: 'rlabel',
            chartHeight: '17',
            positionX: '2',
          },
        ],
      },
    ],
    type: 'cockpit',
    cockpitConf: {
      screenWidth: 100,
      viewName: '大屏',
      background: '#000000',
      screenHeight: 100,
      fontColor: '#FFFFFF',
      categoryId: '',
    },
  },
  categoryName: null,
  edit: false,
  delete: false,
};

// 用于保存的看板数据
var saveBoardData = {
  name: '大屏',
  layout: {
    rows: [
      {
        type: 'widget',
        widgets: [
          {
            widgetId: 16,
            chartHeight: '23',
            chartWidth: '27',
            bgColor: 'none',
            positionX: '2',
            positionY: '7',
            domId: 'chart_1632966987527',
            border: 'url(imgs/cockpit/border/01.png)',
          },
          {
            widgetId: 9,
            chartHeight: '18',
            chartWidth: '51',
            bgColor: 'none',
            positionX: '47',
            positionY: '2',
            domId: 'chart_1632966997721',
            border: 'url(imgs/cockpit/border/01.png)',
          },
        ],
      },
      {
        type: 'other',
        others: [
          {
            type: 'clock',
            chartWidth: '21',
            chartHeight: '17',
            positionX: '2',
            positionY: '75',
            chartStyle: '',
            cockpitConfChartCSS: {
              textFontSize: '12',
              labelPadding: '5',
              labelFontSize: '12',
              textFontWeight: 'normal',
              textColor: '#FFFFFF',
              labelColor: '#FFFFFF',
              textFormat: 'yyyy-MM-dd hh:mm:ss',
            },
            jsonData: {},
            domId: 'clock_1632967073624',
          },
          {
            type: 'rlabel',
            chartWidth: '21',
            chartHeight: '17',
            positionX: '2',
            positionY: '41',
            chartStyle: '',
            cockpitConfChartCSS: { titleColor: '#FFFFFF' },
            jsonData: { value: 'HexCockpit可视化产品，创造属于您的日常运营监控大屏！' },
            domId: 'rlabel_1632967077811',
          },
        ],
      },
    ],
    type: 'cockpit',
    cockpitConf: {
      screenWidth: 100,
      viewName: '大屏',
      background: '#000000',
      screenHeight: 100,
      fontColor: '#FFFFFF',
      categoryId: '',
    },
  },
  categoryId: '',
  id: '3',
};
